### ISSUE TITLE
Create a GitHub Action

### ISSUE THREAD

**Issue by GuillaumeDesforges** [tweag/FawltyDeps#431] opened 2024-05-03 08:43 UTC

**Comment by obscurerichard** [comment] 2024-05-03 15:18
👋🏻 I'm interested in taking this on on.

**Comment by mknorps** [comment] 2024-05-06 07:26
I am closing this issue as a duplicate of https://github.com/tweag/FawltyDeps/issues/170.
@obscurerichard You are warmly welcome to work on that :heart:

**Closed by mknorps** 2024-05-06 07:26 UTC
