### ISSUE TITLE
Action published in GitHub Marketplace?

### ISSUE THREAD

**Issue by vreuter** [tweag/FawltyDeps#332] opened 2023-06-12 09:24 UTC
Has this been considered? I'd find it useful! See: https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A GitHub action to run `FawltyDeps` published to the GitHub Marketplace, similar e.g. to how `black` may be run as an Action.

**Describe alternatives you've considered**
Running FawltyDeps manually and locally, or writing a custom workflow to define an action repo-by-repo, generally copying and pasting the same `.yaml` file.

**Comment by jherland** [comment] 2023-06-13 11:03
I like the idea, but AFAICS this is a duplicate of #170? Feel free to reopen if I missed something.

**Closed by jherland** 2023-06-13 11:03 UTC
Labels: duplicate, type: feature request, integration

**Comment by vreuter** [comment] 2023-06-15 13:38
Indeed, #170 covers it, thanks @jherland !
