### ISSUE TITLE
FawltyDeps fails running on itself

### ISSUE THREAD

**Issue by mknorps** [tweag/FawltyDeps#392] opened 2023-11-07 08:52 UTC
**Describe the bug**
When I install from scratch a developer's environment and run `fawltydeps` in it I get following message:
```
(fawltydeps-py3.11) ➜  FawltyDeps git:(main) fawltydeps

These imports appear to be undeclared dependencies:
- 'pkg_resources'

These dependencies appear to be unused (i.e. not imported):
- 'setuptools'
- 'types-setuptools'

For a more verbose report re-run with the `--detailed` option.
```

**To Reproduce**
Run fawltydeps from `poetry shell`.

**Expected behavior**
FawltyDeps does not report any missing or unused dependencies

**Environment**
 - OS name + version: I tested on Ubuntu and Windows.
 - Version of the code:
 ```
(fawltydeps-py3.11) ➜  FawltyDeps git:(main) fawltydeps --version
FawltyDeps v0.13.2
(fawltydeps-py3.11) ➜  FawltyDeps git:(main) which fawltydeps
/home/mknorps/.cache/pypoetry/virtualenvs/fawltydeps-RB6LwJVc-py3.11/bin/fawltydeps
```

**Comment by jherland** [comment] 2023-11-07 11:16
FD runs inside the poetry shell/virtualenv (which lives _outside_ the current dir). FD is apparently not able to automatically find this pyenv. It _should_ find this venv according to this logic:
- No `--pyenv` on command-line, so search for venvs under current dir
- No venv found, so fall back to _current_ venv (we are after running _inside_ the poetry venv).

This last fallback seems to file. Needs more investigation.

**Comment by jherland** [comment] 2023-11-07 14:29
I reproduced this locally, and figured out why the fallback to current virtualenv does not work: The problem is in fact that FD _does_ find Python environments, too many, in fact, and _none_ of them are relevant to analyzing FawltyDeps itself. Running `fawltydeps --list-sources --detailed` illuminates the problem quite well:

```
Sources of Python code:
  fawltydeps/__init__.py (using fawltydeps/ as base for 1st-party imports)
  [...more .py files...]

Sources of declared dependencies:
  pyproject.toml (parsed as a pyproject.toml file)

Python environments:
  tests/sample_projects/no_issues/.venv/lib/python3.10/site-packages (as a source of Python packages)
  tests/sample_projects/pyenv_galore/.venv/lib/python3.10/site-packages (as a source of Python packages)
  tests/sample_projects/pyenv_galore/__pypackages__/3.10/lib (as a source of Python packages)
  tests/sample_projects/pyenv_galore/__pypackages__/3.7/lib (as a source of Python packages)
  tests/sample_projects/pyenv_galore/another-venv/lib/python3.11/site-packages (as a source of Python packages)
  tests/sample_projects/pyenv_galore/another-venv/lib/python3.8/site-packages (as a source of Python packages)
  tests/sample_projects/pyenv_galore/poetry2nix_result/lib/python3.9/site-packages (as a source of Python packages)
```

There are several virtualenvs found under `tests/sample_projects`, but none contain the relevant modules needed to analyize FawltyDeps itself. Nevertheless, finding these virtualenvs means that we don't fall back to using the current venv.

Possible explanations and potential solutions:

- The current behavior is fine, but FawltyDeps is "special", i.e., we don't expect many Python projects to contain virtualenvs as part of their test suite, and it is OK to require FD to fail with default options, and have to work around this with one of these options:
  - Pass `--pyenv` directly, like the `self_test()` in `noxfile.py` already does.
  - Once [the `--ignore` PR](https://github.com/tweag/FawltyDeps/pull/387) has been merged, it probably makes sense to add `tests/sample_projects` to be ignored inside `[tool.fawltydeps]` in our `pyproject.toml`.
- The current behavior is _not_ fine. We should fix the logic around what virtualenvs we use in our analysis (i.e. the logic [illustrated here](https://www.tweag.io/static/c1e215728a5dc43db07764d1c7a03f71/00fb1/finding_local_pyenvs.png) in our second blog post), so that this does not happen. For example:
  - Whether or not `--pyenv` is used, we should _always_ also include the current virtualenv in our analysis. This is quite a dramatic change, and means that the user can no longer use `--pyenv` to exclude the current virtualenv. If we go for this, we might also want to add another CLI option specifically to control the inclusion/exclusion of the current virtualenv.
  - Slightly weaker/cleverer: When `--pyenv` is _not_ used, we will search for pyenvs, as before, but we will also use the current environment, whether or not we also find other venvs.

I think I'm currently in favor of the very last option, but I'm eager to hear about perspectives or better solutions that I have missed. What do you think?

**Comment by jherland** [comment] 2023-11-09 11:25
I tried to implement the solution (last option) I mentioned above, but ran into annoying difficulties with the way our `Settings` and CLI parser are organized: In order to have different behavior when `--pyenv` is used vs when `basepaths` is used, we need to stop collapsing `basepaths` into `.code/.deps/.pyenvs` at CLI parsing time (instead the logic that defaults empty `.code/.deps/.pyenvs` to `basepaths` must happen at _time-of-use_, i.e. somewhere in `Analysis`). Anyway, having `.basepaths` as a separate `Settings` members then causes some discomfort about existing behavior (it no longer makes easy to have `.basepaths` at the CLI level override `.code/.deps/.pyenvs` from the config file, as `.basepaths` now exists as a separate field in the config file, too).

In summary, things get _more_ complex and unintuitive, when I wanted to make them simpler. So I'm not sure this is the best way forward after all...

@mknorps: yesterday, [you hinted an alternative solution on Slack](https://moduscreate.slack.com/archives/C04AAQP8C85/p1699426161573999?thread_ts=1699368472.036089&cid=C04AAQP8C85), where we add a separate resolver to always look at the current env where FD is running. I guess that is much closer to the first change I proposed above ("Whether or not `--pyenv` is used, we should always also include the current virtualenv in our analysis."). I'm coming around to this idea, although I'm undecided on whether it needs to be possible to disable this for the user.

I started playing around with the code a little, and so far this seems like it's much easier to implement, and it should work with almost no changes to our test suite at all(!)

**Closed** 2023-11-10 09:52 UTC
Labels: type: bug
